FROM golang:1.17-alpine AS build
EXPOSE 8000


WORKDIR /project/
ADD horoscope /project/
ADD main.go /project/
ADD Website.html /project/

ADD go.mod /project/
RUN go mod download 

# ADD /grpc-go/ /src/
# COPY grpc-go/ /src/
# RUN go env -w GO111MODULE=off
# RUN go env GOPROXY=http://proxy.golang.org,direct
RUN CGO_ENABLED=0 go build -o /project/main.go

FROM alpine
COPY --from=build /main /main
ENTRYPOINT ["/main"]