FROM golang:1.17-alpine AS build
# FROM httpd:latest
EXPOSE 8000

# COPY horoscope /go/src/finalProject/horoscope
# COPY /Website.html /user/local/apache2/htdocs/

WORKDIR /finalProject/

COPY . ./

# COPY go.mod ./
RUN go mod download 


# COPY horoscope ./
# ADD main.go ./
#COPY Website.html /user/local/apache2/htdocs/


# RUN CGO_ENABLED=0 go build -o /main

# FROM alpine
# COPY --from=build /main /main

CMD [ "go", "run", "main.go" ]

# ENTRYPOINT ["/main"]