apiVersion: v1
kind: Service
metadata:
  name: horoscope-service
spec:
  selector:
    app: horoscope
  type: NodePort
  ports:
  - protocol: TCP
    port: 8000
    name: horoscope
  type: NodePort
  selector:
    app: horoscope
    
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: horoscope
spec:
  selector:
    matchLabels:
      app: horoscope
  replicas: 1
  template:
    metadata:
      labels:
        app: horoscope
    spec:
      containers:
        - name: horoscope-service
          image: ecastro1/finalproject
          ports:
            - containerPort: 8000


